/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleissue16756;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void otherLibraryMethod() {
	System.out.println("other libary method log");
    }

}
